"""add drink reviews table

Revision ID: 387f48faeed6
Revises: 87b69a80442c
Create Date: 2026-07-06 10:46:35.357400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387f48faeed6'
down_revision: Union[str, Sequence[str], None] = '87b69a80442c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drink_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 10', name='ck_drink_reviews_rating'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drink_reviews_category'), 'drink_reviews', ['category'], unique=False)
    op.create_index(op.f('ix_drink_reviews_chat_id'), 'drink_reviews', ['chat_id'], unique=False)
    op.create_index(op.f('ix_drink_reviews_created_at'), 'drink_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_drink_reviews_is_favorite'), 'drink_reviews', ['is_favorite'], unique=False)
    op.create_index(op.f('ix_drink_reviews_name'), 'drink_reviews', ['name'], unique=False)
    op.create_index(op.f('ix_drink_reviews_rating'), 'drink_reviews', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drink_reviews_rating'), table_name='drink_reviews')
    op.drop_index(op.f('ix_drink_reviews_name'), table_name='drink_reviews')
    op.drop_index(op.f('ix_drink_reviews_is_favorite'), table_name='drink_reviews')
    op.drop_index(op.f('ix_drink_reviews_created_at'), table_name='drink_reviews')
    op.drop_index(op.f('ix_drink_reviews_chat_id'), table_name='drink_reviews')
    op.drop_index(op.f('ix_drink_reviews_category'), table_name='drink_reviews')
    op.drop_table('drink_reviews')
    # ### end Alembic commands ###
